apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: keycloak
  name: keycloak
  namespace: ort-server
spec:
  hostname:
    hostname: keycloak
  instances: 1 # TODO 3
  resources:
    requests:
      cpu: "1"
      memory: "1Gi"
    limits:
      cpu: "4"
      memory: "2Gi"
  db:
    vendor: postgres
    url: "jdbc:postgresql://postgresql-rw:5432/app" # FIXME hard-coded dbname
    poolMinSize: 5
    poolInitialSize: 5
    poolMaxSize: 30
    usernameSecret:
      name: postgresql-app
      key: username
    passwordSecret:
      name: postgresql-app
      key: password
  http:
    tlsSecret: keycloak-tls
